### ISSUE TITLE
Cython - generování WaToru

### ISSUE THREAD

**Issue by vanclmil** [hroncok/wator#1]
Ahoj,
mám problém s rychlostí generování WaToru.
Náhodnost dělám tak, že si vygeneruju permutaci indexů `pos = numpy.random.permutation(size)`, po které potom iteruji a podle indexu hodím do WaToru potvoru.
Nicméně samotné `numpy.random.permutation` trvá už skoro těch čtvrt sekundy a následná iterace ještě něco déle (hádám, že to je kvůli zběsilému skákání po paměti způsobenému tou permutací indexů).
Myslíte, že by tenhle způsob šel nějak zoptimalizovat, nebo mám zvolit jiný způsob náhodnosti?
Díky.
Milan

**Comment by hroncok** [comment]
Moc se omlouvám, neměl jsem na tomhle repu watch. Kdybych příště dlouho nereagoval, dej mi mention (napiš @hroncok).

**Comment by vanclmil** [comment]
Ok, nic se něděje, tušil jsem že to moc zoptimalizovat nepůjde, tak jsem to předělal.
